swagger: "2.0"
info:
  version: "1.0.0"
  title: "GPT2-Titles"
host: "main-gpt2-titles-tr-lox.endpoint.ainize.ai"
basePath: "/generate"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "generate titles by tags"
      summary: "create title"
      description: "please input tags of title"
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "query"
        type: 'string'
        in: "query"
        description: "title of review"
        required: true
        items:
          type: "string"
          default: "tags united states,introduce usa title"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
